### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by godver3** [godver3/cli_battery#1]
- [ ] Create and implement auto-update schedule
- [x] Implement poster storage
- [x] Determine "evergreen" items
- [x] Create schema for DB
- [ ] Test all routes through gRPC
